Meilleur report d'erreur si le premier runtest echoue (par suite d'une erreur du compilo C).

diff --git a/sources/config/autoconf b/sources/config/autoconf
--- a/sources/config/autoconf
+++ b/sources/config/autoconf
@@ -27,8 +27,11 @@ case "$1,$2,$3" in
          echo "sizeof(long) != sizeof(long *)."
          echo "Caml Light won't run on this architecture."
          exit 2;;
-      *) echo "This architecture seems to be neither 32 bits nor 64 bits."
+  ?,?,?) echo "This architecture seems to be neither 32 bits nor 64 bits."
          echo "Caml Light won't run on this architecture."
+         exit 2;;
+      *) echo "Unable to compile the test program."
+         echo "Make sure the C compiler is properly installed."
          exit 2;;
 esac
 
